# 启用自动更新
auto-updates: true
# 启用自动错误汇报
# 建议启用，将在发生错误时自动将错误报告汇报给作者
# 仅会将SFCalc/Slimefun/Minecraft的版本以及错误内容汇报
# 不会收集其他内容
error-reports: false

# Header string ("Recipe for Synthetic Diamond")
# %1 name of item
header-string: "&e&n%1所需材料:"

# Header amount string ("Recipe for 2 Explosive Pickaxe")
# %1 name of item
# %2 amount of item
header-amount-string: "&e&n%2个%1所需材料:"

# Stack string ("202 (12 x16 + 2)")
# %1 amount of item
# %2 amount of stacks of item
# %3 stack size of item
# %4 amount of item that doesn't fit into a stack
stack-string: "&e%1 (%2 x %3 + %4)"

# Amount string ("20 of Iron Ore")
# %1 name of item
# %2 amount of item (can also be stack string)
amount-string: "&e%2 个 %1"

# Needed string ("10 more Silicon needed")
# %1 name of item
# %2 amount of item (can also be stack string)
needed-string: "&e还需要 %2 个 %1"

# Item not found string ("That item was not found!")
no-item-string: "&c物品未找到!"

# Not a number string ("That's not a number!")
not-a-number-string: "&c无效的数字!"

# Too many categories/items strings
# ("That many categories/items is not supported yet. Please use the command form of the calculator.")
category-error-string: "&c分类过多"
item-error-string: "&c物品过多"

not-a-player-string: "&c只有玩家才能执行该指令!"

invalid-number-string: "&c无效数字!"

options:
  # 使用碳而不是煤作为基础材料
  # 来进行计算
  use-carbon-instead-of-coal: true


